#:kivy 1.0
<MyGrid>:
    GridLayout:
        cols:1
        size: root.width, root.height
    
        GridLayout:
            cols:2

            Label:
                text: "Name: "
                color: 1,1,0,1
                font_size: 24

            TextInput:
                multiline:False

            Label:
                text: "Email: "

            TextInput:
                multiline:False

        Button:
            text:"Submit"
            on_press: app.btn()